import type { Team } from "./types";

// Lista drużyn (do dropdownu "mistrz świata"). Flagi jako emoji — zgodnie z prototypem.
export const TEAMS: Team[] = [
  { name: "Algieria", flag: "🇩🇿" },
  { name: "Anglia", flag: "🏴" },
  { name: "Arabia Saud.", flag: "🇸🇦" },
  { name: "Argentyna", flag: "🇦🇷" },
  { name: "Australia", flag: "🇦🇺" },
  { name: "Austria", flag: "🇦🇹" },
  { name: "Belgia", flag: "🇧🇪" },
  { name: "Bośnia", flag: "🇧🇦" },
  { name: "Brazylia", flag: "🇧🇷" },
  { name: "Chorwacja", flag: "🇭🇷" },
  { name: "Curaçao", flag: "🇨🇼" },
  { name: "Czechy", flag: "🇨🇿" },
  { name: "DR Konga", flag: "🇨🇩" },
  { name: "Egipt", flag: "🇪🇬" },
  { name: "Ekwador", flag: "🇪🇨" },
  { name: "Francja", flag: "🇫🇷" },
  { name: "Ghana", flag: "🇬🇭" },
  { name: "Haiti", flag: "🇭🇹" },
  { name: "Hiszpania", flag: "🇪🇸" },
  { name: "Holandia", flag: "🇳🇱" },
  { name: "Irak", flag: "🇮🇶" },
  { name: "Iran", flag: "🇮🇷" },
  { name: "Japonia", flag: "🇯🇵" },
  { name: "Jordania", flag: "🇯🇴" },
  { name: "Kanada", flag: "🇨🇦" },
  { name: "Katar", flag: "🇶🇦" },
  { name: "Kolumbia", flag: "🇨🇴" },
  { name: "Korea Płd.", flag: "🇰🇷" },
  { name: "Maroko", flag: "🇲🇦" },
  { name: "Meksyk", flag: "🇲🇽" },
  { name: "Niemcy", flag: "🇩🇪" },
  { name: "Norwegia", flag: "🇳🇴" },
  { name: "Nowa Zelandia", flag: "🇳🇿" },
  { name: "Panama", flag: "🇵🇦" },
  { name: "Paragwaj", flag: "🇵🇾" },
  { name: "Portugalia", flag: "🇵🇹" },
  { name: "RPA", flag: "🇿🇦" },
  { name: "Rep. Ziel. Przylądka", flag: "🇨🇻" },
  { name: "Senegal", flag: "🇸🇳" },
  { name: "Szkocja", flag: "🏴" },
  { name: "Szwajcaria", flag: "🇨🇭" },
  { name: "Szwecja", flag: "🇸🇪" },
  { name: "Tunezja", flag: "🇹🇳" },
  { name: "Turcja", flag: "🇹🇷" },
  { name: "USA", flag: "🇺🇸" },
  { name: "Urugwaj", flag: "🇺🇾" },
  { name: "Uzbekistan", flag: "🇺🇿" },
  { name: "Wyb. K. Słoniowej", flag: "🇨🇮" },
];

export const TOURNEY_START_ISO = "2026-06-11T19:00:00Z";

export const PRIZES: Record<number, string> = { 0: "600 zł", 1: "250 zł", 2: "150 zł" };
